# Makefile of the 'main' routines.
# Paul Boersma, 10 September 2011

include ../makefile.defs

CPPFLAGS = -I ../melder -I ../sys -I ../fon -I ../stat

.PHONY: clean

jpraat.o: jpraat.cpp


clean:
	$(RM) jpraat.o

